### ISSUE TITLE
WebPack issue

### ISSUE THREAD

**Issue by sm2017** [xotahal/react-native-material-ui#180]
Want to try use `react-native-web` 

I have some error like the following

```
ERROR in ./node_modules/react-native-material-ui/src/Dialog/DialogDefaultActions.react.js
Module parse failed: node_modules\react-native-material-ui\src\Dialog\DialogDefaultActions.react.js Unexpected token (48:12)
You may need an appropriate loader to handle this file type.
| 
|         return (
|             <View style={styles.defaultActionsContainer}>
|                 {actions.map(action =>
|                     <Button
 @ ./node_modules/react-native-material-ui/src/index.js 15:0-86
 @ ./node_modules/react-native-material-ui/index.js
 @ ./src/containers/App.js
 @ ./src/containers/Root.js
 @ ./index.web.js

```

Currently I use `babel-loader` and `react-native` as `presets`

**Comment by dalcib** [comment]
You need to add this path `/node_modules[\\\/]react-native-*/` to your `include` field in the babel-loader config in webpack.

Take a look in this example https://github.com/dalcib/react-native-material-ui-web-app  that use react-app-rewired to configure create-react-app to do that.

**Comment by sm2017** [comment]
@dalcib thanks for your reply , I add the path to `include` field , currently I have new issue
 

```
ERROR in ./src/containers/Root.js
Module parse failed: \src\containers\Root.js Unexpected token (13:6)
You may need an appropriate loader to handle this file type.
|   render() {
|     return (
|       <Provider store={store}>
|         <App />
|       </Provider>
 @ ./index.web.js 6:0-41
```

before using `react-native-material-ui` my webpack configs works well

This is part of my webpack config

```js
{
...
module: {
    loaders: [{
      test: /\.jsx?$/,
      loader: 'babel-loader',
      include: [
       /node_modules[\\\/]react-native-*/,
      ],
      exclude: /node_modules/,
      query: {
        presets: ['react-native'],
      },
    }
...
}
```

**Comment by sm2017** [comment]
@dalcib thanks a lot for your reply , after adding to include field I have the following error

```
ERROR in ./node_modules/react-native-web/dist/index.js
Module build failed: ReferenceError: Unknown plugin "transform-react-remove-prop-types" specified in "node_modules\\react-native-web\\package.json" at 0, attempted to resolve relative to "node_modules\\react-native-web"
  at node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
  at Array.map (native)
  at Function.normalisePlugins (node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
  at OptionManager.mergeOptions (node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
  at OptionManager.init (node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
  at File.initOptions (node_modules\babel-core\lib\transformation\file\index.js:212:65)
  at new File (node_modules\babel-core\lib\transformation\file\index.js:135:24)
  at Pipeline.transform (node_modules\babel-core\lib\transformation\pipeline.js:46:16)
  at transpile (node_modules\babel-loader\lib\index.js:49:20)
  at Object.module.exports (node_modules\babel-loader\lib\index.js:174:20)
 @ ./index.web.js 5:0-41
```

**Comment by dalcib** [comment]
Try  `npm i babel-plugin-transform-react-remove-prop-types`

**Comment by sm2017** [comment]
@dalcib , Yes it works , I use `yarn` , Do you know why `babel-plugin-transform-react-remove-prop-types` is `devDependencies` of `react-native-web` https://github.com/necolas/react-native-web/blob/master/package.json#L75 , But `yarn install` don't install it? Why I must add it again?

**Comment by sm2017** [comment]
@dalcib Do you know why `yarn` don't installed dev dependencies of dependency ?

**Comment by dalcib** [comment]
I'm sorry. I use only `npm`.

**Comment by dalcib** [comment]
@sm2017, take a look in this: https://github.com/necolas/react-native-web/issues/607#issuecomment-322530912

**Comment by iegik** [comment]
Like that?

webpack.config.dev.js
```
{
        test: /\.js$/,
        exclude: /node_modules/,
        include: /node_modules[\\\/]react-native-*/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react'],
          plugins: [['react-transform', {
            transforms: [{
              transform: 'react-transform-hmr',
              imports: ['react'],
              // this is important for Webpack HMR:
              locals: ['module']
            }],
          }], ['transform-react-remove-prop-types']],
        },
      }
```

.babelrc
```
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source", "transform-react-remove-prop-types"]
    }
  }
```
