### ISSUE TITLE
BackAndroid is deprecated

### ISSUE THREAD

**Issue by JoaoBGusmao** [xotahal/react-native-material-ui#449]
Following this stack, we can note that src/utils/index.js is importing `BackAndroid as DeprecatedBackAndroid,` and that's what causes the error.

```
 Test suite failed to run

    Invariant Violation: BackAndroid is deprecated and has been removed from this package. Use BackHandler instead

      at invariant (node_modules/invariant/invariant.js:40:15)
      at Object.invariant [as BackAndroid] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:373:5)
      at Object.DeprecatedBackAndroid (node_modules/react-native-material-ui/src/utils/index.js:9:36)
      at Object.<anonymous> (node_modules/react-native-material-ui/src/RippleFeedback/RippleFeedbackIOS.react.js:13:1)

```

**Comment by JoaoBGusmao** [comment]
I can see it was fixed already, but it doesn't seem to have been published to npm
https://github.com/xotahal/react-native-material-ui/blob/master/src/utils/index.js
